# Generated by Django 2.1 on 2018-12-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provasobi', '0002_auto_20181217_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problema',
            name='enunciadoproblema',
            field=models.TextField(blank=True, db_column='enunciadoProblema', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='problema',
            name='tituloproblema',
            field=models.TextField(blank=True, db_column='tituloProblema', null=True),
        ),
    ]
