# Generated by Django 2.1 on 2018-12-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provasobi', '0004_auto_20181217_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problema',
            name='tituloproblema',
            field=models.TextField(blank=True, db_column='tituloProblema', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='problema',
            unique_together={('codprova', 'tituloproblema')},
        ),
    ]
