# Generated by Django 2.1.4 on 2018-12-18 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provasobi', '0005_auto_20181217_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gabarito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Explicação')),
                ('imagem', models.ImageField(upload_to='', verbose_name='Imagem Explicativa ')),
            ],
        ),
        migrations.AddField(
            model_name='prova',
            name='urlgabarito',
            field=models.URLField(blank=True, db_column='urlGabarito', null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='questao',
            unique_together={('codproblema', 'numeroquestao')},
        ),
        migrations.AddField(
            model_name='gabarito',
            name='codquestao',
            field=models.ForeignKey(blank=True, db_column='codQuestao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='provasobi.Questao'),
        ),
    ]
