# Generated by Django 2.1.4 on 2018-12-18 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provasobi', '0006_auto_20181218_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gabarito',
            name='codquestao',
            field=models.OneToOneField(db_column='codQuestao', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='provasobi.Questao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gabarito',
            name='imagem',
            field=models.ImageField(null=True, upload_to='', verbose_name='Imagem Explicativa '),
        ),
        migrations.AlterField(
            model_name='gabarito',
            name='texto',
            field=models.TextField(null=True, verbose_name='Explicação'),
        ),
    ]
