# Generated by Django 2.1.4 on 2018-12-18 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provasobi', '0007_auto_20181218_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gabarito',
            name='codquestao',
        ),
        migrations.AddField(
            model_name='questao',
            name='explicativo',
            field=models.TextField(null=True, verbose_name='Explicação'),
        ),
        migrations.AddField(
            model_name='questao',
            name='explicativo_imagem',
            field=models.ImageField(null=True, upload_to='', verbose_name='Imagem Explicativa '),
        ),
        migrations.DeleteModel(
            name='Gabarito',
        ),
    ]
