# Generated by Django 2.1.4 on 2018-12-19 11:07

from django.db import migrations, models
import provasobi.models


class Migration(migrations.Migration):

    dependencies = [
        ('provasobi', '0008_auto_20181218_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problema',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=provasobi.models.Problema.recorte, verbose_name='Recorte'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='explicativo',
            field=models.TextField(blank=True, null=True, verbose_name='Explicação'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='explicativo_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem Explicativa '),
        ),
        migrations.AlterField(
            model_name='questao',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=provasobi.models.Questao.recorte, verbose_name='Recorte'),
        ),
    ]
