# Generated by Django 2.1.4 on 2019-01-09 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provasobi', '0009_auto_20181219_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativa',
            name='codquestao',
            field=models.ForeignKey(blank=True, db_column='codQuestao', null=True, on_delete=django.db.models.deletion.CASCADE, to='provasobi.Questao'),
        ),
        migrations.AlterField(
            model_name='problema',
            name='codprova',
            field=models.ForeignKey(blank=True, db_column='codProva', null=True, on_delete=django.db.models.deletion.CASCADE, to='provasobi.Prova'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='codproblema',
            field=models.ForeignKey(blank=True, db_column='codProblema', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cod_problemas_questao', to='provasobi.Problema'),
        ),
    ]
