# Generated by Django 2.1.4 on 2019-01-10 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provasobi', '0010_auto_20190109_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternativa',
            options={'managed': True, 'ordering': ['letraalternativa']},
        ),
    ]
