# Generated by Django 2.1.4 on 2019-01-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provasobi', '0012_auto_20190110_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='alternativas',
            field=models.TextField(null=True, verbose_name='Alternativas'),
        ),
    ]
