# Generated by Django 2.1.4 on 2019-01-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provasobi', '0013_questao_alternativas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='alternativas',
            field=models.TextField(blank=True, null=True, verbose_name='Alternativas'),
        ),
    ]
